name: Check dependencies

on:
  push:
    branches:
      - master
      - develop
      - 'dependabot/npm_and_yarn/**'

jobs:
  # yarn で peerDependences の制約を満たすか検証する
  yarn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
        yarn: [1.13, 1.22]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Install fail-on-stderr
        run: go get github.com/pocke/fail-on-stderr

      - name: yarn policies set-version ${{ matrix.yarn }}
        run: yarn policies set-version ${{ matrix.yarn }}

      # ref: https://github.com/yarnpkg/yarn/issues/4594
      - name: yarn install --frozen-lockfile
        run: fail-on-stderr yarn install --frozen-lockfile --json
