name: Node CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: node-

      - name: yarn install --frozen-lockfile
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: yarn run run-s -l check:*
